name: Upload Changed Files to Azure Blob Storage

on:
  push:
    branches:
      - 'main'
    paths:
      - 'scripts/**'  # Replace with the folder or files you care about

jobs:
  sync-to-azure:
    runs-on: ubuntu-latest
    environment:
      name: 'AZURE_CREDENTIALS'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Azure using service principal
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}


      - name: Upload files to Azure Blob Storage
        run: |
          az storage blob upload-batch \
            --account-name teststgacct29099 \
            --destination script \
            --source scripts \
            --overwrite
            --sas-token sp=racwdli&st=2025-04-24T21:14:59Z&se=2025-12-31T05:14:59Z&sv=2024-11-04&sr=c&sig=Iwt8BYj9ukn65%2FCaHi9R%2BvtQEi647hDCsvAwvfxL8wQ%3D
